### ISSUE TITLE
Compatibility with molecular barcodes

### ISSUE THREAD

**Issue by wanj2** [crukci-bioinformatics/MGA#2]
Hi,
Some of my libraries that I have tried to put through MGA have an in-line molecular barcode for the first 10-15 bases, which results in ~90% unmapped reads according to MGA. It would be handy if the user could specify to skip N bases from the beginning of each read.

Thanks in advance.

Best wishes,
Jonathan

**Comment by wanj2** [comment]
In the meantime I will clip my FASTQ files. 

J

**Comment by eldrid01** [comment]
HI Jonathan,

Yes, that makes sense and should be straightforward to do. I'm doing some work on MGA right now so will factor this in.

Best,
Matt

**Comment by eldrid01** [comment]
Hi Jonathan,

I've added a --trim-start option to the prepare-pipeline utilty for configuring MGA. This adds a variable called trimStart to the configuration file and allows one to specify the position within sequences from which the trimmed sequences will start. You can specify 16 for example to remove the first 15 bases corresponding to the molecular barcode.

I expect that we'll roll this out along with some other changes to MGA in the near future for our automated data processing and QC pipeline at CRUK-CI, but this will need to be done in discussion with the Genomics Core.

Matt

**Comment by eldrid01** [comment]
Added --trim-start and --trim-length options, available in latest release version 1.4.
