### ISSUE TITLE
Alignments in unexpected sort order

### ISSUE THREAD

**Issue by ghost** [crukci-bioinformatics/MGA#3]
Hi, 

I started to test the 1.4 release. My first test with a handful of fastq files worked fine, however more testing with about 50 fastq files at once gave me some error at the createReport step. Here is the error: 

java.lang.RuntimeException: Alignments in unexpected sort order at line 64 in file /camp/svc/scratch/babs/escudem/demultiplexing/180511_K00102_0206_AHV5VCBBXX/mga-1.4_test/PM17013/temp/1.1.P_acnes.bowtie.alignment 

I attach the file mentioned in the error, although this is not the only alignment file that triggers the problem. 
[1.1.P_acnes.bowtie.alignment.txt](https://github.com/crukci-bioinformatics/MGA/files/2008739/1.1.P_acnes.bowtie.alignment.txt)

Do you know what is causing the error?

Cheers, 
Micka

**Comment by eldrid01** [comment]
Hi Micka,

I've managed to reproduce this and will hopefully have a fix quite soon.

The issue arises with numeric dataset identifiers. Our workflow manager is using a "clever" sorting algorithm that recognizes numeric parts of file names so sorts dataset 8 before dataset 10 in the alignment file you provided. However, the report generation code uses a regular alphabetical sort that would have 10 coming before 8.

Cheers,
Matt

**Comment by eldrid01** [comment]
Hi Micka,

I've fixed this now and tested this on the example I created to reproduce the problem. It's available in the latest release 1.4.1. Please try this out and reopen the issue if necessary.

Thanks
Matt

**Comment by ghost** [comment]
Thanks a lot Matt, that works like a charm now :)
